# Generated by Django 3.2.5 on 2021-08-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches_app', '0002_auto_20210817_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
