# Generated by Django 3.2.5 on 2021-08-19 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches_app', '0005_remove_newsletteremail_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetterEmail',
        ),
    ]
