# Generated by Django 3.2.5 on 2021-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches_app', '0006_delete_newsletteremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Эмаил для рассылки',
                'verbose_name_plural': 'Эмаилы для рассылки',
            },
        ),
    ]
