# Generated by Django 3.2.5 on 2021-08-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches_app', '0007_emailnewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnewsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
